"""Demo content stored in Python collections, as required by the assignment."""

COMICS = [
    {
        "slug": "star-pilot",
        "title": "Звёздный пилот",
        "title_en": "Star Pilot",
        "author": "Мира Ким",
        "genre": "Космос",
        "year": 2026,
        "description": "Юная пилотесса Лея находит сигнал с планеты, которой нет ни на одной карте.",
        "description_en": "Young pilot Leia discovers a signal from a planet missing from every map.",
        "cover": "images/star-pilot.svg",
        "accent": "violet",
        "panels": [
            {
                "image": "images/star-pilot.svg",
                "caption": "Сигнал принят",
                "text": "— Центр, вы это слышите? На частоте появляется чей-то голос.",
            },
            {
                "image": "images/star-pilot.svg",
                "caption": "Прыжок в неизвестность",
                "text": "Лея нажала на рычаг. Звёзды вытянулись в серебряные нити.",
            },
            {
                "image": "images/star-pilot.svg",
                "caption": "Новая орбита",
                "text": "За иллюминатором зажёгся фиолетовый рассвет.",
            },
        ],
    },
    {
        "slug": "tea-witch",
        "title": "Чайная ведьма",
        "title_en": "The Tea Witch",
        "author": "Алекс Рой",
        "genre": "Фэнтези",
        "year": 2025,
        "description": "В маленькой чайной Нора заваривает напитки, которые возвращают людям смелость.",
        "description_en": "In a tiny teahouse, Nora brews drinks that return courage to people.",
        "cover": "images/tea-witch.svg",
        "accent": "amber",
        "panels": [
            {
                "image": "images/tea-witch.svg",
                "caption": "Тихий заказ",
                "text": "— Мне бы чашку чего-нибудь, что не даст сдаться.",
            },
            {
                "image": "images/tea-witch.svg",
                "caption": "Рецепт из лунного света",
                "text": "Нора добавила лепесток ночной розы и улыбнулась.",
            },
            {
                "image": "images/tea-witch.svg",
                "caption": "Первый глоток",
                "text": "Тепло разлилось по комнате, и дождь за окном стал тише.",
            },
        ],
    },
    {
        "slug": "city-of-clouds",
        "title": "Город облаков",
        "title_en": "City of Clouds",
        "author": "Илья Север",
        "genre": "Приключения",
        "year": 2024,
        "description": "Курьер Яр доставляет письма между парящими островами и ищет свой дом.",
        "description_en": "Courier Yar delivers letters between floating islands while looking for home.",
        "cover": "images/city-of-clouds.svg",
        "accent": "sky",
        "panels": [
            {
                "image": "images/city-of-clouds.svg",
                "caption": "Письмо в облаках",
                "text": "Адрес был написан на обратной стороне старого компаса.",
            },
            {
                "image": "images/city-of-clouds.svg",
                "caption": "Встречный ветер",
                "text": "Парус раскрылся, и остров медленно поплыл навстречу солнцу.",
            },
            {
                "image": "images/city-of-clouds.svg",
                "caption": "Следующий маршрут",
                "text": "Яр увидел вдали огни города, которого не было вчера.",
            },
        ],
    },
]

UI_TEXT = {
    "ru": {
        "site_name": "Панелька",
        "tagline": "место для историй",
        "library": "Библиотека",
        "settings": "Настройки",
        "about": "О проекте",
        "hero_kicker": "Читай медленнее",
        "hero_title": "Истории, которые хочется рассматривать",
        "hero_text": "Открой небольшую коллекцию авторских комиксов и настрой пространство под себя.",
        "open_comic": "Читать выпуск",
        "continue_reading": "Продолжить чтение",
        "new_collection": "Свежая коллекция",
        "collection_text": "Три коротких выпуска для уютного вечера.",
        "by": "Автор",
        "year": "Год",
        "genre": "Жанр",
        "back_library": "Вернуться в библиотеку",
        "appearance": "Внешний вид",
        "appearance_text": "Сделай чтение удобным для глаз. Настройки сохраняются в cookies этого браузера.",
        "theme": "Тема",
        "font_size": "Размер текста",
        "language": "Язык интерфейса",
        "paper": "Бумага",
        "night": "Ночь",
        "neon": "Неон",
        "small": "Маленький",
        "medium": "Средний",
        "large": "Большой",
        "russian": "Русский",
        "english": "English",
        "save": "Сохранить настройки",
        "saved": "Настройки сохранены в cookies",
        "last_read": "Последний выпуск",
        "no_last_read": "Ты ещё не открывал выпуски. Выбери историю выше.",
        "about_title": "Небольшая учебная библиотека",
        "about_text": "Проект создан на Django без базы данных: каталог хранится в списках и словарях Python, а персональные настройки — в cookies.",
        "panel": "Панель",
    },
    "en": {
        "site_name": "Panelka",
        "tagline": "a place for stories",
        "library": "Library",
        "settings": "Settings",
        "about": "About",
        "hero_kicker": "Read slower",
        "hero_title": "Stories worth looking at",
        "hero_text": "Open a small collection of indie comics and tune your reading space.",
        "open_comic": "Read issue",
        "continue_reading": "Continue reading",
        "new_collection": "Fresh collection",
        "collection_text": "Three short issues for a quiet evening.",
        "by": "Author",
        "year": "Year",
        "genre": "Genre",
        "back_library": "Back to library",
        "appearance": "Appearance",
        "appearance_text": "Make reading comfortable for your eyes. Settings are saved in this browser's cookies.",
        "theme": "Theme",
        "font_size": "Text size",
        "language": "Interface language",
        "paper": "Paper",
        "night": "Night",
        "neon": "Neon",
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "russian": "Русский",
        "english": "English",
        "save": "Save settings",
        "saved": "Settings saved in cookies",
        "last_read": "Last issue",
        "no_last_read": "You have not opened an issue yet. Pick a story above.",
        "about_title": "A small learning library",
        "about_text": "Built with Django without a database: the catalog lives in Python lists and dictionaries, while personal settings live in cookies.",
        "panel": "Panel",
    },
}
